### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on closing the demo app

### ISSUE THREAD

**Issue by jfaltermeier** [maketechnology/cefswt#10]
I checked out the demo application for windows. Cool stuff!

I noticed that the VM crashes with an EXCEPTION_ACCESS_VIOLATION when the app gets stopped: 
[hs_err_pid3468.txt](https://github.com/maketechnology/cefswt/files/1180048/hs_err_pid3468.txt)

The log gets created in the .swtcef\3.3029.1611.g44e39a8\windows-x86_64 directory.

**Comment by gzunino** [comment]
Thanks for the report. We are aware of the issue and should be fixed soon.

Please consider donating to move this project ahead! (https://github.com/maketechnology/cefswt#status-and-plan)
