### ISSUE TITLE
macOS crash with chromium 88 in Runtime

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/cefswt#125]
We are testing Equo Chromium SWT Release v88.0.4 - 2022-03-14
The problem occurs on a runtime with macOS.
It is working on a Windows runtime as well with macOS within the Eclipse development environment.

On a runtime with macOS, I get a trap. I’ve attached the log below.

Crashed Thread:        82  Chrome_IOThread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [17321]

Thread 0:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80d489cf2 __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	    0x7ff80d4c1e8f _pthread_mutex_firstfit_lock_wait + 76
2   libsystem_pthread.dylib       	    0x7ff80d4bfd58 _pthread_mutex_firstfit_lock_slow + 204
3   Chromium Embedded Framework   	        0x3f5545b6 cef_time_delta + 3785334

The Mac runtime works fine with safari. It also works with Chromium when run from the eclipse ide. But obviously, there is a problem with the packaged runtime when activating chromium.

[trap.log](https://github.com/equoplatform/chromium-swt/files/8303203/trap.log)

**Comment by lonelion** [comment]
Already fixed in newer versions.
