### ISSUE TITLE
webp image support

### ISSUE THREAD

**Issue by heinrichWeichert** [maketechnology/cefswt#128]
Hi equodev devs, 

I integrated the "trial" into an RCP application but it seems that the CEF dist does not support webp images.
Could that be correct?

**Comment by mauropuravida** [comment]
Hi @heinrichWeichert , I have tried to view a webp image online or locally and have been able to view it without problems. Can you provide an example that reproduces the problem?

**Comment by lonelion** [comment]
Hi @heinrichWeichert ,

I'm curious if you successfully managed to integrate the Equo Chromium trial edition, were you able to solve the issue you were having? Please let us know if you need help.

**Comment by heinrichWeichert** [comment]
I could not, but I managed to workaround the issue by transcoding to png. Thanks anyway.
This can be closed as it seems that the problem occurred only with my setup
