### ISSUE TITLE
Swing?

### ISSUE THREAD

**Issue by Link-Kou** [maketechnology/cefswt#129]
When will it be launched?

**Comment by mauropuravida** [comment]
Hi @Link-Kou!. In the next major open source release, the possibility to create and manage browsers using the Swing toolkit within the ChromiumBrowser API will be available. It will also be a more complete version that will allow some new functionalities.

Currently, you can make use of our trial version of Chromium at [https://equo.dev/landing/chromium](https://equo.dev/landing/chromium) or if you are a JxBrowser user you can use our drop-in replacement in the section "**Migrating from JxBrowser? Check out our drop-in replacement**". Both have a more complete API with support for the Swing toolkit.

You can find all the documentation needed to use trial drop in replacement at [Equo Chromium Documentation](https://docs.equoplatform.com/chromium/95.x/getting-started/migrating-from-jxbrowser.html).

**Comment by Link-Kou** [comment]
@mauropuravida 

BUG，Unable to apply
![image](https://user-images.githubusercontent.com/22113151/231025399-64468d37-04bb-4e88-b875-d3a067eeeb31.png)

**Comment by Link-Kou** [comment]
@mauropuravida  
macOS 
Does ARM support it?

**Comment by mauropuravida** [comment]
Hi @Link-Kou. You need to use a work email. The current trial does not have ARM support at the moment, it is likely to be added to the trial version in the future. At the moment ARM support is in the commercial version.

**Comment by mauropuravida** [comment]
@Link-Kou We have made the change to the trial application form so that it is not just a work email. You can now try again with gmail.

**Comment by mauropuravida** [comment]
@Link-Kou changes have been made so that the new trials generated contain ARM support.

**Comment by Link-Kou** [comment]
@mauropuravida 
Thank you. I have made an application.
