### ISSUE TITLE
Doesn't work in eclipse

### ISSUE THREAD

**Issue by quantmode** [maketechnology/cefswt#131]

**Comment by quantmode** [comment]
Upon further investigation, it turns out that your installer modifies the eclipse.ini file to use your own launcher. However, when uninstalling your product, your launcher is not changed back to the original, and that causes the font display issue. 

I had to restore my eclipse.ini from backup in order to undo your product's changes. 

This product seems pretty dodgy. A) it doesn't work. I was unable to import the browser class. B) Modifying the user's eclipse.ini without the user's knowledge. C) Failing to reset it back again when uninstalling, which then causes problems with their eclipse environment (in my case the fonts were all rendering fuzzy). 

Definitely gives off a vibe of spying on your users.

**Comment by lonelion** [comment]
Hi @quantmode,

Installing the Chromium integration for Eclipse from the Eclipse marketplace will automatically replace all SWT native browsers of your Eclipse IDE. The Chromium integration for Eclipse targets users who want to have a seamless and cross-platform experience across Windows, macOS, and Linux environments without manual adjustments.

If you want to develop with Equo Chromium (i.e. importing the com.equo package), you have to use Equo Chromium as a library in your Java or Eclipse-based application. To do so you may get a ready-to-use build requesting a trial here: https://www.equo.dev/get-a-trial

Let me know if that works.

**Comment by quantmode** [comment]
I'll skip. You deleted the comment in which I described how your product alters eclipse.ini but does not return it to its original state on uninstallation, which leaves eclipse broken, and leaves it running from your own proprietary launcher, unbenownst to the user.

**Comment by lonelion** [comment]
Hi @quantmode,

Your comment was deleted because it was malicious and defamatory. In Chromium integration for Eclipse, which replaces all SWT native browsers of an Eclipse installation and is not intended to be used for development, we use a custom launcher to support Wayland in Linux systems, see the doc here:

https://docs.equoplatform.com/chromium/116.x/developing/specific-requirements.html#_wayland_support

The only thing the launcher does is set the GDK_BACKEND env var and call the Xlib function to activate thread synchronization before launching the app. However, you're right there is an issue when uninstalling Chromium integration for Eclipse, it should return the eclipse.ini to the original state. We will fix it soon.

**Comment by quantmode** [comment]
Malicious and defamatory? It's not defamation if it's the truth, which you just confirmed.

I wasted an hour trying to figure out what your product had done to render my eclipse install unusable.

**Comment by lonelion** [comment]
You know what you said and you went way beyond than describing a bug.

Closing this issue since it's not relevant to this topic.

**Comment by quantmode** [comment]
The "bug" is you replace the eclipse launcher with your own in the eclipse.ini file, and then you leave it there after uninstallation.

If it wasn't for the fact that your launcher caused some kind of resolution mismatch between eclipse and my native screen, so that all fonts were rendered blurry, I would never have noticed. As it was, it took me a lot of frustrating sleuthing to figure out what had happened.

Any user that installs your product and doesn't tickle the same issue will henceforth be running their eclipse off your launcher, even if they believe they have uninstalled the product. That's a security hole a mile-wide, and it's natural to speculate on why you would  choose to distribute your product in such a manner. It also makes me wonder what else was left behind after the uninstall.
